import type { Hotel, RaceAccommodationRecommendation } from "../../types/accommodation.ts";

// Ctrip Mini Program paths are opaque affiliate actions generated by Ctrip Open Platform.
// Store each complete path exactly as generated and pass it to wx.navigateToMiniProgram
// unchanged. Do not parse, rewrite, normalize, or replace its query parameters.
// Parameters such as inday/outday are controlled by Ctrip, not RaceNext business data.
const hotels: Hotel[] = [
  {
    hotelId: "echarm-beijing-qianmen",
    hotelName: "宜尚酒店（北京天安门广场前门地铁站店）",
    actions: {
      wechat: {
        type: "mini_program",
        appId: "wx0e6ed4f51db9d078",
        path: "/pages/hotel/detail/index?id=99891175&inday=2026-09-16&outday=2026-09-17&biz=1&ouid=link&AllianceID=9729651&sid=327120872&guid=10650054344_share_9729651_1789370105112&sct=open_platform",
      },
    },
  },
  {
    hotelId: "ji-beijing-wangfujing",
    hotelName: "全季酒店（北京天安门广场王府井店）",
    actions: {
      wechat: {
        type: "mini_program",
        appId: "wx0e6ed4f51db9d078",
        path: "/pages/hotel/detail/index?id=67228147&inday=2026-09-16&outday=2026-09-17&biz=1&ouid=link&AllianceID=9729651&sid=327120872&guid=10650054344_share_9729651_1789370254633&sct=open_platform",
      },
    },
  },
  {
    hotelId: "fairfield-beijing-olympic",
    hotelName: "万豪万枫酒店（北京鸟巢国家会议中心店）",
    actions: {
      wechat: {
        type: "mini_program",
        appId: "wx0e6ed4f51db9d078",
        path: "/pages/hotel/detail/index?id=48583994&inday=2026-09-16&outday=2026-09-17&biz=1&ouid=link&AllianceID=9729651&sid=327120872&guid=10650054344_share_9729651_1789370551047&sct=open_platform",
      },
    },
  },
];

const recommendations: RaceAccommodationRecommendation[] = [
  {
    recommendationId: "beijing-marathon-2026-echarm-qianmen",
    editionId: "beijing-marathon-2026",
    hotelId: "echarm-beijing-qianmen",
    reasonType: "start_proximity",
    recommendationTitle: "比赛日最省事",
    recommendationReason: "紧邻 2 / 8 号线前门站，前往北马起点路线简单。比赛日地铁出站后可步行前往广场检录区域，减少打车和换乘的不确定性。",
    evidenceBasis: "racenext_judgment",
    evidenceRefs: [],
    displayOrder: 1,
  },
  {
    recommendationId: "beijing-marathon-2026-ji-wangfujing",
    editionId: "beijing-marathon-2026",
    hotelId: "ji-beijing-wangfujing",
    reasonType: "transport",
    recommendationTitle: "赛前赛后更方便",
    recommendationReason: "位于王府井商圈，餐饮和城市出行选择丰富，适合希望比赛之外减少生活安排成本的跑者；对外地参赛者抵达和离开北京也相对方便。",
    evidenceBasis: "racenext_judgment",
    evidenceRefs: [],
    displayOrder: 2,
  },
  {
    recommendationId: "beijing-marathon-2026-fairfield-olympic",
    editionId: "beijing-marathon-2026",
    hotelId: "fairfield-beijing-olympic",
    reasonType: "finish_proximity",
    recommendationTitle: "完赛后最省力",
    recommendationReason: "位于奥体终点片区，完赛后返回酒店距离短，适合更看重赛后快速洗澡、休息和恢复的跑者，避免再长距离乘坐公共交通返回住处。",
    evidenceBasis: "racenext_judgment",
    evidenceRefs: [],
    displayOrder: 3,
  },
];

export function getRaceAccommodationRecommendations(editionId: string): Array<{
  hotel: Hotel;
  recommendation: RaceAccommodationRecommendation;
}> {
  return recommendations
    .filter((recommendation) => recommendation.editionId === editionId)
    .sort((left, right) => left.displayOrder - right.displayOrder)
    .map((recommendation) => {
      const hotel = hotels.find((candidate) => candidate.hotelId === recommendation.hotelId);
      if (!hotel) throw new Error(`Unknown accommodation hotel: ${recommendation.hotelId}`);
      return { hotel, recommendation };
    });
}
