import type { Hotel, RaceAccommodationRecommendation } from "../../types/accommodation.ts";

// Ctrip Mini Program paths are opaque affiliate actions generated by Ctrip Open Platform.
// Store each complete path exactly as generated and pass it to wx.navigateToMiniProgram
// unchanged. Do not parse, rewrite, normalize, or replace its query parameters.
// Parameters such as inday/outday are controlled by Ctrip, not RaceNext business data.
const hotels: Hotel[] = [
  {
    hotelId: "echarm-beijing-qianmen",
    hotelName: "宜尚酒店（北京天安门广场前门地铁站店）",
    actions: {
      wechat: {
        type: "mini_program",
        appId: "wx0e6ed4f51db9d078",
        path: "/pages/hotel/detail/index?id=99891175&inday=2026-09-16&outday=2026-09-17&biz=1&ouid=link&AllianceID=9729651&sid=327120872&guid=10650054344_share_9729651_1789370105112&sct=open_platform",
      },
    },
  },
  {
    hotelId: "ji-beijing-wangfujing",
    hotelName: "全季酒店（北京天安门广场王府井店）",
    actions: {
      wechat: {
        type: "mini_program",
        appId: "wx0e6ed4f51db9d078",
        path: "/pages/hotel/detail/index?id=67228147&inday=2026-09-16&outday=2026-09-17&biz=1&ouid=link&AllianceID=9729651&sid=327120872&guid=10650054344_share_9729651_1789370254633&sct=open_platform",
      },
    },
  },
  {
    hotelId: "fairfield-beijing-olympic",
    hotelName: "万豪万枫酒店（北京鸟巢国家会议中心店）",
    actions: {
      wechat: {
        type: "mini_program",
        appId: "wx0e6ed4f51db9d078",
        path: "/pages/hotel/detail/index?id=48583994&inday=2026-09-16&outday=2026-09-17&biz=1&ouid=link&AllianceID=9729651&sid=327120872&guid=10650054344_share_9729651_1789370551047&sct=open_platform",
      },
    },
  },
  {
    hotelId: "yazhi-xian-zhonglou-yongningmen",
    hotelName: "西安钟楼永宁门雅致酒店",
    actions: {
      wechat: {
        type: "mini_program",
        appId: "wx0e6ed4f51db9d078",
        path: "/pages/hotel/detail/index?id=120417383&inday=2026-09-23&outday=2026-09-24&biz=1&ouid=link&AllianceID=9729651&sid=327120872&guid=10650054344_share_9729651_1789981783929&sct=open_platform",
      },
    },
  },
  {
    hotelId: "citigo-xian-zhonglou-nanmen",
    hotelName: "CitiGO Hotel 西安钟楼南门店",
    actions: {
      wechat: {
        type: "mini_program",
        appId: "wx0e6ed4f51db9d078",
        path: "/pages/hotel/detail/index?id=29790928&inday=2026-09-23&outday=2026-09-24&biz=1&ouid=link&AllianceID=9729651&sid=327120872&guid=10650054344_share_9729651_1789981839974&sct=open_platform",
      },
    },
  },
  {
    hotelId: "ji-xian-aoti-convention",
    hotelName: "全季西安奥体国际会展中心酒店",
    actions: {
      wechat: {
        type: "mini_program",
        appId: "wx0e6ed4f51db9d078",
        path: "/pages/hotel/detail/index?id=111253418&inday=2026-09-23&outday=2026-09-24&biz=1&ouid=link&AllianceID=9729651&sid=327120872&guid=10650054344_share_9729651_1789981897661&sct=open_platform",
      },
    },
  },
  {
    hotelId: "chengdu-jinsha-century",
    hotelName: "成都金沙世纪酒店",
    actions: {
      wechat: {
        type: "mini_program",
        appId: "wx0e6ed4f51db9d078",
        path: "/pages/hotel/detail/index?id=2272797&inday=2026-09-23&outday=2026-09-24&biz=1&ouid=link&AllianceID=9729651&sid=327120872&guid=10650054344_share_9729651_1789983024767&sct=open_platform",
      },
    },
  },
  {
    hotelId: "orange-chengdu-yipintianxia-jinsha-museum",
    hotelName: "桔子酒店（成都一品天下金沙博物馆地铁站店）",
    actions: {
      wechat: {
        type: "mini_program",
        appId: "wx0e6ed4f51db9d078",
        path: "/pages/hotel/detail/index?id=98999166&inday=2026-09-23&outday=2026-09-24&biz=1&ouid=link&AllianceID=9729651&sid=327120872&guid=10650054344_share_9729651_1789983064850&sct=open_platform",
      },
    },
  },
  {
    hotelId: "yitel-chengdu-caida-wenhuagong",
    hotelName: "和颐至格酒店（成都西南财大文化宫地铁站店）",
    actions: {
      wechat: {
        type: "mini_program",
        appId: "wx0e6ed4f51db9d078",
        path: "/pages/hotel/detail/index?id=1669899&inday=2026-09-23&outday=2026-09-24&biz=1&ouid=link&AllianceID=9729651&sid=327120872&guid=10650054344_share_9729651_1789983097816&sct=open_platform",
      },
    },
  },
  {
    hotelId: "chengdu-hongyu",
    hotelName: "成都泓宇酒店",
    actions: {
      wechat: {
        type: "mini_program",
        appId: "wx0e6ed4f51db9d078",
        path: "/pages/hotel/detail/index?id=1432148&inday=2026-09-23&outday=2026-09-24&biz=1&ouid=link&AllianceID=9729651&sid=327120872&guid=10650054344_share_9729651_1789983132105&sct=open_platform",
      },
    },
  },
  {
    hotelId: "holiday-inn-chengdu-century-city-east",
    hotelName: "成都世纪城假日酒店-东楼",
    actions: {
      wechat: {
        type: "mini_program",
        appId: "wx0e6ed4f51db9d078",
        path: "/pages/hotel/detail/index?id=429874&inday=2026-09-23&outday=2026-09-24&biz=1&ouid=link&AllianceID=9729651&sid=327120872&guid=10650054344_share_9729651_1789983165797&sct=open_platform",
      },
    },
  },
  {
    hotelId: "dada-linhai",
    hotelName: "临海畣畣 dádá 民宿",
    actions: {
      wechat: {
        type: "mini_program",
        appId: "wx0e6ed4f51db9d078",
        path: "/pages/hotel/detail/index?id=127002105&inday=2026-09-23&outday=2026-09-24&biz=1&ouid=link&AllianceID=9729651&sid=327120872&guid=10650054344_share_9729651_1789984020007&sct=open_platform",
      },
    },
  },
  {
    hotelId: "sanfuyizhai-linhai",
    hotelName: "临海三抚一宅民宿（紫阳街台州府城店）",
    actions: {
      wechat: {
        type: "mini_program",
        appId: "wx0e6ed4f51db9d078",
        path: "/pages/hotel/detail/index?id=31572972&inday=2026-09-23&outday=2026-09-24&biz=1&ouid=link&AllianceID=9729651&sid=327120872&guid=10650054344_share_9729651_1789984047649&sct=open_platform",
      },
    },
  },
  {
    hotelId: "taizhou-fuchengyin",
    hotelName: "台州府城印酒店",
    actions: {
      wechat: {
        type: "mini_program",
        appId: "wx0e6ed4f51db9d078",
        path: "/pages/hotel/detail/index?id=125785721&inday=2026-09-23&outday=2026-09-24&biz=1&ouid=link&AllianceID=9729651&sid=327120872&guid=10650054344_share_9729651_1789984128706&sct=open_platform",
      },
    },
  },
  {
    hotelId: "qianshan-m-plus-linhai",
    hotelName: "芊杉·M⁺民宿（临海紫阳街台州府城店）",
    actions: {
      wechat: {
        type: "mini_program",
        appId: "wx0e6ed4f51db9d078",
        path: "/pages/hotel/detail/index?id=131562564&inday=2026-09-23&outday=2026-09-24&biz=1&ouid=link&AllianceID=9729651&sid=327120872&guid=10650054344_share_9729651_1789984181370&sct=open_platform",
      },
    },
  },
  {
    hotelId: "kaiyuan-mingting-linhai",
    hotelName: "台州临海开元名庭酒店",
    actions: {
      wechat: {
        type: "mini_program",
        appId: "wx0e6ed4f51db9d078",
        path: "/pages/hotel/detail/index?id=133280371&inday=2026-09-23&outday=2026-09-24&biz=1&ouid=link&AllianceID=9729651&sid=327120872&guid=10650054344_share_9729651_1789984212838&sct=open_platform",
      },
    },
  },
];

const recommendations: RaceAccommodationRecommendation[] = [
  {
    recommendationId: "beijing-marathon-2026-echarm-qianmen",
    editionId: "beijing-marathon-2026",
    hotelId: "echarm-beijing-qianmen",
    reasonType: "start_proximity",
    recommendationTitle: "比赛日最省事",
    recommendationReason: "紧邻 2 / 8 号线前门站，前往北马起点路线简单。比赛日地铁出站后可步行前往广场检录区域，减少打车和换乘的不确定性。",
    evidenceBasis: "racenext_judgment",
    evidenceRefs: [],
    displayOrder: 1,
  },
  {
    recommendationId: "beijing-marathon-2026-ji-wangfujing",
    editionId: "beijing-marathon-2026",
    hotelId: "ji-beijing-wangfujing",
    reasonType: "transport",
    recommendationTitle: "赛前赛后更方便",
    recommendationReason: "位于王府井商圈，餐饮和城市出行选择丰富，适合希望比赛之外减少生活安排成本的跑者；对外地参赛者抵达和离开北京也相对方便。",
    evidenceBasis: "racenext_judgment",
    evidenceRefs: [],
    displayOrder: 2,
  },
  {
    recommendationId: "beijing-marathon-2026-fairfield-olympic",
    editionId: "beijing-marathon-2026",
    hotelId: "fairfield-beijing-olympic",
    reasonType: "finish_proximity",
    recommendationTitle: "完赛后最省力",
    recommendationReason: "位于奥体终点片区，完赛后返回酒店距离短，适合更看重赛后快速洗澡、休息和恢复的跑者，避免再长距离乘坐公共交通返回住处。",
    evidenceBasis: "racenext_judgment",
    evidenceRefs: [],
    displayOrder: 3,
  },
  {
    recommendationId: "xian-marathon-2026-yazhi-xian-zhonglou-yongningmen",
    editionId: "xian-marathon-2026",
    hotelId: "yazhi-xian-zhonglou-yongningmen",
    reasonType: "start_proximity",
    recommendationTitle: "比赛日最省事",
    recommendationReason: "位于永宁门附近，适合优先步行前往起点，减少比赛日清晨交通的不确定性。",
    evidenceBasis: "racenext_judgment",
    evidenceRefs: [],
    displayOrder: 1,
  },
  {
    recommendationId: "xian-marathon-2026-citigo-xian-zhonglou-nanmen",
    editionId: "xian-marathon-2026",
    hotelId: "citigo-xian-zhonglou-nanmen",
    reasonType: "transport",
    recommendationTitle: "古城内兼顾起跑",
    recommendationReason: "位于钟楼—南门核心区域，在保持起跑便利的同时，也方便把参赛和古城体验结合起来。",
    evidenceBasis: "racenext_judgment",
    evidenceRefs: [],
    displayOrder: 2,
  },
  {
    recommendationId: "xian-marathon-2026-ji-xian-aoti-convention",
    editionId: "xian-marathon-2026",
    hotelId: "ji-xian-aoti-convention",
    reasonType: "finish_proximity",
    recommendationTitle: "全马完赛后更省事",
    recommendationReason: "位于奥体片区，更适合把全马完赛后的返程便利放在首位的跑者；比赛日则需要提前安排前往永宁门起点的交通。",
    evidenceBasis: "racenext_judgment",
    evidenceRefs: [],
    displayOrder: 3,
  },
  {
    recommendationId: "chengdu-marathon-2026-chengdu-jinsha-century",
    editionId: "chengdu-marathon-2026",
    hotelId: "chengdu-jinsha-century",
    reasonType: "runner_feedback",
    recommendationTitle: "往届跑者实测",
    recommendationReason: "位于金沙片区，往届已有成马跑者实际入住，去起点也比较方便，适合希望参考真实参赛住宿经验的跑者。",
    evidenceBasis: "mixed",
    evidenceRefs: [],
    displayOrder: 2,
  },
  {
    recommendationId: "chengdu-marathon-2026-orange-chengdu-yipintianxia-jinsha-museum",
    editionId: "chengdu-marathon-2026",
    hotelId: "orange-chengdu-yipintianxia-jinsha-museum",
    reasonType: "start_proximity",
    recommendationTitle: "起点最直接",
    recommendationReason: "位于金沙遗址核心区域，适合把比赛日清晨少折腾、方便到达起点放在第一位的跑者。",
    evidenceBasis: "racenext_judgment",
    evidenceRefs: [],
    displayOrder: 1,
  },
  {
    recommendationId: "chengdu-marathon-2026-yitel-chengdu-caida-wenhuagong",
    editionId: "chengdu-marathon-2026",
    hotelId: "yitel-chengdu-caida-wenhuagong",
    reasonType: "transport",
    recommendationTitle: "交通更均衡",
    recommendationReason: "位于文化宫片区，在保持金沙起点可达性的同时，也方便赛前赛后的城市出行。",
    evidenceBasis: "racenext_judgment",
    evidenceRefs: [],
    displayOrder: 3,
  },
  {
    recommendationId: "chengdu-marathon-2026-chengdu-hongyu",
    editionId: "chengdu-marathon-2026",
    hotelId: "chengdu-hongyu",
    reasonType: "runner_feedback",
    recommendationTitle: "实用型起点选择",
    recommendationReason: "靠近金沙起点区域，也有往届成都马跑者实际入住反馈，适合不一定要住到起点门口、但希望比赛日出发足够省事的跑者。",
    evidenceBasis: "mixed",
    evidenceRefs: [],
    displayOrder: 4,
  },
  {
    recommendationId: "chengdu-marathon-2026-holiday-inn-chengdu-century-city-east",
    editionId: "chengdu-marathon-2026",
    hotelId: "holiday-inn-chengdu-century-city-east",
    reasonType: "finish_proximity",
    recommendationTitle: "全马完赛后更省事",
    recommendationReason: "位于世纪城片区，更适合把全马完赛后的返程便利放在首位的跑者；比赛日则需要提前前往金沙起点。",
    evidenceBasis: "racenext_judgment",
    evidenceRefs: [],
    displayOrder: 5,
  },
  {
    recommendationId: "tsaigu-kuocang-2026-dada-linhai",
    editionId: "tsaigu-kuocang-2026",
    hotelId: "dada-linhai",
    reasonType: "runner_feedback",
    recommendationTitle: "古城核心·跑者实测",
    recommendationReason: "位于临海古城核心区域，也有往届柴古跑者实际入住经验，适合希望住在起终点附近、同时参考真实参赛住宿体验的跑者。",
    evidenceBasis: "mixed",
    evidenceRefs: [],
    displayOrder: 2,
  },
  {
    recommendationId: "tsaigu-kuocang-2026-sanfuyizhai-linhai",
    editionId: "tsaigu-kuocang-2026",
    hotelId: "sanfuyizhai-linhai",
    reasonType: "start_proximity",
    recommendationTitle: "离起终点最近",
    recommendationReason: "距兴善门很近，适合希望凌晨出门后直接步行去起点、长距离完赛后也尽快回住宿的跑者。",
    evidenceBasis: "racenext_judgment",
    evidenceRefs: [],
    displayOrder: 1,
  },
  {
    recommendationId: "tsaigu-kuocang-2026-taizhou-fuchengyin",
    editionId: "tsaigu-kuocang-2026",
    hotelId: "taizhou-fuchengyin",
    reasonType: "start_proximity",
    recommendationTitle: "酒店型步行方案",
    recommendationReason: "仍在兴善门步行范围内，同时更接近标准酒店住宿形态，适合不太想住小型民宿的跑者。",
    evidenceBasis: "racenext_judgment",
    evidenceRefs: [],
    displayOrder: 3,
  },
  {
    recommendationId: "tsaigu-kuocang-2026-qianshan-m-plus-linhai",
    editionId: "tsaigu-kuocang-2026",
    hotelId: "qianshan-m-plus-linhai",
    reasonType: "start_proximity",
    recommendationTitle: "古城内步行优先",
    recommendationReason: "位于台州府城核心区域，起终点、古城和赛前赛后活动都集中在步行范围内。",
    evidenceBasis: "racenext_judgment",
    evidenceRefs: [],
    displayOrder: 4,
  },
  {
    recommendationId: "tsaigu-kuocang-2026-kaiyuan-mingting-linhai",
    editionId: "tsaigu-kuocang-2026",
    hotelId: "kaiyuan-mingting-linhai",
    reasonType: "start_proximity",
    recommendationTitle: "标准酒店平衡型",
    recommendationReason: "距兴善门比前几家稍远，但仍处于合理步行范围，适合希望住标准酒店、又不想比赛日依赖车辆的跑者。",
    evidenceBasis: "racenext_judgment",
    evidenceRefs: [],
    displayOrder: 5,
  },
];

export function getRaceAccommodationRecommendations(editionId: string): Array<{
  hotel: Hotel;
  recommendation: RaceAccommodationRecommendation;
}> {
  return recommendations
    .filter((recommendation) => recommendation.editionId === editionId)
    .sort((left, right) => left.displayOrder - right.displayOrder)
    .map((recommendation) => {
      const hotel = hotels.find((candidate) => candidate.hotelId === recommendation.hotelId);
      if (!hotel) throw new Error(`Unknown accommodation hotel: ${recommendation.hotelId}`);
      return { hotel, recommendation };
    });
}
