import type { Hotel, RaceAccommodationRecommendation } from "../../types/accommodation.ts";

// Ctrip Mini Program paths are opaque affiliate actions generated by Ctrip Open Platform.
// Store each complete path exactly as generated and pass it to wx.navigateToMiniProgram
// unchanged. Do not parse, rewrite, normalize, or replace its query parameters.
// Parameters such as inday/outday are controlled by Ctrip, not RaceNext business data.
const hotels: Hotel[] = [
  {
    hotelId: "echarm-beijing-qianmen",
    hotelName: "宜尚酒店（北京天安门广场前门地铁站店）",
    actions: {
      wechat: {
        type: "mini_program",
        appId: "wx0e6ed4f51db9d078",
        path: "/pages/hotel/detail/index?id=99891175&inday=2026-09-16&outday=2026-09-17&biz=1&ouid=link&AllianceID=9729651&sid=327120872&guid=10650054344_share_9729651_1789370105112&sct=open_platform",
      },
    },
  },
  {
    hotelId: "ji-beijing-wangfujing",
    hotelName: "全季酒店（北京天安门广场王府井店）",
    actions: {
      wechat: {
        type: "mini_program",
        appId: "wx0e6ed4f51db9d078",
        path: "/pages/hotel/detail/index?id=67228147&inday=2026-09-16&outday=2026-09-17&biz=1&ouid=link&AllianceID=9729651&sid=327120872&guid=10650054344_share_9729651_1789370254633&sct=open_platform",
      },
    },
  },
  {
    hotelId: "fairfield-beijing-olympic",
    hotelName: "万豪万枫酒店（北京鸟巢国家会议中心店）",
    actions: {
      wechat: {
        type: "mini_program",
        appId: "wx0e6ed4f51db9d078",
        path: "/pages/hotel/detail/index?id=48583994&inday=2026-09-16&outday=2026-09-17&biz=1&ouid=link&AllianceID=9729651&sid=327120872&guid=10650054344_share_9729651_1789370551047&sct=open_platform",
      },
    },
  },
  {
    hotelId: "yazhi-xian-zhonglou-yongningmen",
    hotelName: "西安钟楼永宁门雅致酒店",
    actions: {
      wechat: {
        type: "mini_program",
        appId: "wx0e6ed4f51db9d078",
        path: "/pages/hotel/detail/index?id=120417383&inday=2026-09-23&outday=2026-09-24&biz=1&ouid=link&AllianceID=9729651&sid=327120872&guid=10650054344_share_9729651_1789981783929&sct=open_platform",
      },
    },
  },
  {
    hotelId: "citigo-xian-zhonglou-nanmen",
    hotelName: "CitiGO Hotel 西安钟楼南门店",
    actions: {
      wechat: {
        type: "mini_program",
        appId: "wx0e6ed4f51db9d078",
        path: "/pages/hotel/detail/index?id=29790928&inday=2026-09-23&outday=2026-09-24&biz=1&ouid=link&AllianceID=9729651&sid=327120872&guid=10650054344_share_9729651_1789981839974&sct=open_platform",
      },
    },
  },
  {
    hotelId: "ji-xian-aoti-convention",
    hotelName: "全季西安奥体国际会展中心酒店",
    actions: {
      wechat: {
        type: "mini_program",
        appId: "wx0e6ed4f51db9d078",
        path: "/pages/hotel/detail/index?id=111253418&inday=2026-09-23&outday=2026-09-24&biz=1&ouid=link&AllianceID=9729651&sid=327120872&guid=10650054344_share_9729651_1789981897661&sct=open_platform",
      },
    },
  },
  {
    hotelId: "chengdu-jinsha-century",
    hotelName: "成都金沙世纪酒店",
    actions: {
      wechat: {
        type: "mini_program",
        appId: "wx0e6ed4f51db9d078",
        path: "/pages/hotel/detail/index?id=2272797&inday=2026-09-23&outday=2026-09-24&biz=1&ouid=link&AllianceID=9729651&sid=327120872&guid=10650054344_share_9729651_1789983024767&sct=open_platform",
      },
    },
  },
  {
    hotelId: "orange-chengdu-yipintianxia-jinsha-museum",
    hotelName: "桔子酒店（成都一品天下金沙博物馆地铁站店）",
    actions: {
      wechat: {
        type: "mini_program",
        appId: "wx0e6ed4f51db9d078",
        path: "/pages/hotel/detail/index?id=98999166&inday=2026-09-23&outday=2026-09-24&biz=1&ouid=link&AllianceID=9729651&sid=327120872&guid=10650054344_share_9729651_1789983064850&sct=open_platform",
      },
    },
  },
  {
    hotelId: "yitel-chengdu-caida-wenhuagong",
    hotelName: "和颐至格酒店（成都西南财大文化宫地铁站店）",
    actions: {
      wechat: {
        type: "mini_program",
        appId: "wx0e6ed4f51db9d078",
        path: "/pages/hotel/detail/index?id=1669899&inday=2026-09-23&outday=2026-09-24&biz=1&ouid=link&AllianceID=9729651&sid=327120872&guid=10650054344_share_9729651_1789983097816&sct=open_platform",
      },
    },
  },
  {
    hotelId: "chengdu-hongyu",
    hotelName: "成都泓宇酒店",
    actions: {
      wechat: {
        type: "mini_program",
        appId: "wx0e6ed4f51db9d078",
        path: "/pages/hotel/detail/index?id=1432148&inday=2026-09-23&outday=2026-09-24&biz=1&ouid=link&AllianceID=9729651&sid=327120872&guid=10650054344_share_9729651_1789983132105&sct=open_platform",
      },
    },
  },
  {
    hotelId: "holiday-inn-chengdu-century-city-east",
    hotelName: "成都世纪城假日酒店-东楼",
    actions: {
      wechat: {
        type: "mini_program",
        appId: "wx0e6ed4f51db9d078",
        path: "/pages/hotel/detail/index?id=429874&inday=2026-09-23&outday=2026-09-24&biz=1&ouid=link&AllianceID=9729651&sid=327120872&guid=10650054344_share_9729651_1789983165797&sct=open_platform",
      },
    },
  },
  {
    hotelId: "dada-linhai",
    hotelName: "临海畣畣 dádá 民宿",
    actions: {
      wechat: {
        type: "mini_program",
        appId: "wx0e6ed4f51db9d078",
        path: "/pages/hotel/detail/index?id=127002105&inday=2026-09-23&outday=2026-09-24&biz=1&ouid=link&AllianceID=9729651&sid=327120872&guid=10650054344_share_9729651_1789984020007&sct=open_platform",
      },
    },
  },
  {
    hotelId: "sanfuyizhai-linhai",
    hotelName: "临海三抚一宅民宿（紫阳街台州府城店）",
    actions: {
      wechat: {
        type: "mini_program",
        appId: "wx0e6ed4f51db9d078",
        path: "/pages/hotel/detail/index?id=31572972&inday=2026-09-23&outday=2026-09-24&biz=1&ouid=link&AllianceID=9729651&sid=327120872&guid=10650054344_share_9729651_1789984047649&sct=open_platform",
      },
    },
  },
  {
    hotelId: "taizhou-fuchengyin",
    hotelName: "台州府城印酒店",
    actions: {
      wechat: {
        type: "mini_program",
        appId: "wx0e6ed4f51db9d078",
        path: "/pages/hotel/detail/index?id=125785721&inday=2026-09-23&outday=2026-09-24&biz=1&ouid=link&AllianceID=9729651&sid=327120872&guid=10650054344_share_9729651_1789984128706&sct=open_platform",
      },
    },
  },
  {
    hotelId: "qianshan-m-plus-linhai",
    hotelName: "芊杉·M⁺民宿（临海紫阳街台州府城店）",
    actions: {
      wechat: {
        type: "mini_program",
        appId: "wx0e6ed4f51db9d078",
        path: "/pages/hotel/detail/index?id=131562564&inday=2026-09-23&outday=2026-09-24&biz=1&ouid=link&AllianceID=9729651&sid=327120872&guid=10650054344_share_9729651_1789984181370&sct=open_platform",
      },
    },
  },
  {
    hotelId: "kaiyuan-mingting-linhai",
    hotelName: "台州临海开元名庭酒店",
    actions: {
      wechat: {
        type: "mini_program",
        appId: "wx0e6ed4f51db9d078",
        path: "/pages/hotel/detail/index?id=133280371&inday=2026-09-23&outday=2026-09-24&biz=1&ouid=link&AllianceID=9729651&sid=327120872&guid=10650054344_share_9729651_1789984212838&sct=open_platform",
      },
    },
  },
  {
    hotelId: "xiakeju-ninghai-xuxiake",
    hotelName: "宁波宁海霞客居酒店（徐霞客大道店）",
    actions: {
      wechat: {
        type: "mini_program",
        appId: "wx0e6ed4f51db9d078",
        path: "/pages/hotel/detail/index?id=1701230&inday=2026-09-24&outday=2026-09-25&biz=1&ouid=link&AllianceID=9729651&sid=327120872&guid=10650054344_share_9729651_1790043627133&sct=open_platform",
      },
    },
  },
  {
    hotelId: "atour-ninghai-xizi-international",
    hotelName: "宁波宁海西子国际亚朵酒店",
    actions: {
      wechat: {
        type: "mini_program",
        appId: "wx0e6ed4f51db9d078",
        path: "/pages/hotel/detail/index?id=114605638&inday=2026-09-24&outday=2026-09-25&biz=1&ouid=link&AllianceID=9729651&sid=327120872&guid=10650054344_share_9729651_1790043663265&sct=open_platform",
      },
    },
  },
  {
    hotelId: "hanting-ninghai-xizi-plaza",
    hotelName: "汉庭酒店（宁海西子国际广场店）",
    actions: {
      wechat: {
        type: "mini_program",
        appId: "wx0e6ed4f51db9d078",
        path: "/pages/hotel/detail/index?id=109887818&inday=2026-09-24&outday=2026-09-25&biz=1&ouid=link&AllianceID=9729651&sid=327120872&guid=10650054344_share_9729651_1790043703024&sct=open_platform",
      },
    },
  },
  {
    hotelId: "ninghai-world-trade-center",
    hotelName: "宁海世贸中心大酒店",
    actions: {
      wechat: {
        type: "mini_program",
        appId: "wx0e6ed4f51db9d078",
        path: "/pages/hotel/detail/index?id=1302028&inday=2026-09-24&outday=2026-09-25&biz=1&ouid=link&AllianceID=9729651&sid=327120872&guid=10650054344_share_9729651_1790043735313&sct=open_platform",
      },
    },
  },
  {
    hotelId: "tiangang-manfei-ninghai",
    hotelName: "天港漫非酒店（宁海店）",
    actions: {
      wechat: {
        type: "mini_program",
        appId: "wx0e6ed4f51db9d078",
        path: "/pages/hotel/detail/index?id=67463121&inday=2026-09-24&outday=2026-09-25&biz=1&ouid=link&AllianceID=9729651&sid=327120872&guid=10650054344_share_9729651_1790043771020&sct=open_platform",
      },
    },
  },
  {
    hotelId: "atour-shanghai-bund-nanjing-east",
    hotelName: "上海外滩南京东路亚朵酒店",
    actions: {
      wechat: {
        type: "mini_program",
        appId: "wx0e6ed4f51db9d078",
        path: "/pages/hotel/detail/index?id=444194&inday=2026-09-24&outday=2026-09-25&biz=1&ouid=link&AllianceID=9729651&sid=327120872&guid=10650054344_share_9729651_1790046858865&sct=open_platform",
      },
    },
  },
  {
    hotelId: "jinglai-bushe-shanghai-bund",
    hotelName: "景莱·不舍酒店（上海南京东路外滩店）",
    actions: {
      wechat: {
        type: "mini_program",
        appId: "wx0e6ed4f51db9d078",
        path: "/pages/hotel/detail/index?id=132520733&inday=2026-09-24&outday=2026-09-25&biz=1&ouid=link&AllianceID=9729651&sid=327120872&guid=10650054344_share_9729651_1790046891590&sct=open_platform",
      },
    },
  },
  {
    hotelId: "metropolo-shanghai-bund-nanjing-road",
    hotelName: "上海外滩南京路步行街锦江都城酒店",
    actions: {
      wechat: {
        type: "mini_program",
        appId: "wx0e6ed4f51db9d078",
        path: "/pages/hotel/detail/index?id=1114675&inday=2026-09-24&outday=2026-09-25&biz=1&ouid=link&AllianceID=9729651&sid=327120872&guid=10650054344_share_9729651_1790047146691&sct=open_platform",
      },
    },
  },
  {
    hotelId: "radisson-shanghai-olympic-club",
    hotelName: "上海奥林匹克俱乐部丽笙酒店",
    actions: {
      wechat: {
        type: "mini_program",
        appId: "wx0e6ed4f51db9d078",
        path: "/pages/hotel/detail/index?id=127319172&inday=2026-09-24&outday=2026-09-25&biz=1&ouid=link&AllianceID=9729651&sid=327120872&guid=10650054344_share_9729651_1790047207692&sct=open_platform",
      },
    },
  },
  {
    hotelId: "metropolo-shanghai-xujiahui-nanhuating",
    hotelName: "锦江都城酒店（上海徐家汇南华亭宾馆）",
    actions: {
      wechat: {
        type: "mini_program",
        appId: "wx0e6ed4f51db9d078",
        path: "/pages/hotel/detail/index?id=396373&inday=2026-09-24&outday=2026-09-25&biz=1&ouid=link&AllianceID=9729651&sid=327120872&guid=10650054344_share_9729651_1790047234883&sct=open_platform",
      },
    },
  },
  {
    hotelId: "mercure-guangzhou-tianhe-sports-center",
    hotelName: "广州天河体育中心美居酒店",
    actions: {
      wechat: {
        type: "mini_program",
        appId: "wx0e6ed4f51db9d078",
        path: "/pages/hotel/detail/index?id=90697851&inday=2026-09-24&outday=2026-09-25&biz=1&ouid=link&AllianceID=9729651&sid=327120872&guid=10650054344_share_9729651_1790049420243&sct=open_platform",
      },
    },
  },
  {
    hotelId: "guangzhou-tianhe-hotel-sports-center",
    hotelName: "广州天河大厦（天河体育中心店）",
    actions: {
      wechat: {
        type: "mini_program",
        appId: "wx0e6ed4f51db9d078",
        path: "/pages/hotel/detail/index?id=710694&inday=2026-09-24&outday=2026-09-25&biz=1&ouid=link&AllianceID=9729651&sid=327120872&guid=10650054344_share_9729651_1790049465853&sct=open_platform",
      },
    },
  },
  {
    hotelId: "ji-guangzhou-tianhe-tiyuxilu",
    hotelName: "全季酒店（广州天河体育西路地铁站）",
    actions: {
      wechat: {
        type: "mini_program",
        appId: "wx0e6ed4f51db9d078",
        path: "/pages/hotel/detail/index?id=125122144&inday=2026-09-24&outday=2026-09-25&biz=1&ouid=link&AllianceID=9729651&sid=327120872&guid=10650054344_share_9729651_1790049495110&sct=open_platform",
      },
    },
  },
  {
    hotelId: "hotel-indigo-guangzhou-haixinsha",
    hotelName: "广州海心沙英迪格酒店",
    actions: {
      wechat: {
        type: "mini_program",
        appId: "wx0e6ed4f51db9d078",
        path: "/pages/hotel/detail/index?id=107151174&inday=2026-09-24&outday=2026-09-25&biz=1&ouid=link&AllianceID=9729651&sid=327120872&guid=10650054344_share_9729651_1790049527744&sct=open_platform",
      },
    },
  },
  {
    hotelId: "waifiden-guangzhou-tower-zhujiang-new-town",
    hotelName: "维福顿公寓（广州塔珠江新城店）",
    actions: {
      wechat: {
        type: "mini_program",
        appId: "wx0e6ed4f51db9d078",
        path: "/pages/hotel/detail/index?id=1526389&inday=2026-09-24&outday=2026-09-25&biz=1&ouid=link&AllianceID=9729651&sid=327120872&guid=10650054344_share_9729651_1790049552550&sct=open_platform",
      },
    },
  },
  {
    hotelId: "hampton-shenzhen-dameisha",
    hotelName: "深圳大梅沙希尔顿欢朋酒店",
    actions: {
      wechat: {
        type: "mini_program",
        appId: "wx0e6ed4f51db9d078",
        path: "/pages/hotel/detail/index?id=91417515&inday=2026-09-24&outday=2026-09-25&biz=1&ouid=link&AllianceID=9729651&sid=327120872&guid=10650054344_share_9729651_1790050713448&sct=open_platform",
      },
    },
  },
  {
    hotelId: "junyi-seaview-apartment-shenzhen-dameisha",
    hotelName: "深圳大梅沙君宜全海景公寓",
    actions: {
      wechat: {
        type: "mini_program",
        appId: "wx0e6ed4f51db9d078",
        path: "/pages/hotel/detail/index?id=1887786&inday=2026-09-24&outday=2026-09-25&biz=1&ouid=link&AllianceID=9729651&sid=327120872&guid=10650054344_share_9729651_1790050741674&sct=open_platform",
      },
    },
  },
  {
    hotelId: "remi-shenzhen-dameisha-seaside-park",
    hotelName: "瑞米酒店（深圳大梅沙海滨公园店）",
    actions: {
      wechat: {
        type: "mini_program",
        appId: "wx0e6ed4f51db9d078",
        path: "/pages/hotel/detail/index?id=130373188&inday=2026-09-24&outday=2026-09-25&biz=1&ouid=link&AllianceID=9729651&sid=327120872&guid=10650054344_share_9729651_1790050767596&sct=open_platform",
      },
    },
  },
  {
    hotelId: "zaihaibian-seaview-villa",
    hotelName: "在海边·海景泡池度假别墅",
    actions: {
      wechat: {
        type: "mini_program",
        appId: "wx0e6ed4f51db9d078",
        path: "/pages/hotel/detail/index?id=123097654&inday=2026-09-24&outday=2026-09-25&biz=1&ouid=link&AllianceID=9729651&sid=327120872&guid=10650054344_share_9729651_1790050799012&sct=open_platform",
      },
    },
  },
  {
    hotelId: "tinghai-seaview-residence-dapeng",
    hotelName: "深圳听海·海景居（大鹏所城较场尾沙滩店）",
    actions: {
      wechat: {
        type: "mini_program",
        appId: "wx0e6ed4f51db9d078",
        path: "/pages/hotel/detail/index?id=68522172&inday=2026-09-24&outday=2026-09-25&biz=1&ouid=link&AllianceID=9729651&sid=327120872&guid=10650054344_share_9729651_1790050836722&sct=open_platform",
      },
    },
  },
];

const recommendations: RaceAccommodationRecommendation[] = [
  {
    recommendationId: "beijing-marathon-2026-echarm-qianmen",
    editionId: "beijing-marathon-2026",
    hotelId: "echarm-beijing-qianmen",
    reasonType: "start_proximity",
    recommendationTitle: "比赛日最省事",
    recommendationReason: "紧邻 2 / 8 号线前门站，前往北马起点路线简单。比赛日地铁出站后可步行前往广场检录区域，减少打车和换乘的不确定性。",
    evidenceBasis: "racenext_judgment",
    evidenceRefs: [],
    displayOrder: 1,
  },
  {
    recommendationId: "beijing-marathon-2026-ji-wangfujing",
    editionId: "beijing-marathon-2026",
    hotelId: "ji-beijing-wangfujing",
    reasonType: "transport",
    recommendationTitle: "赛前赛后更方便",
    recommendationReason: "位于王府井商圈，餐饮和城市出行选择丰富，适合希望比赛之外减少生活安排成本的跑者；对外地参赛者抵达和离开北京也相对方便。",
    evidenceBasis: "racenext_judgment",
    evidenceRefs: [],
    displayOrder: 2,
  },
  {
    recommendationId: "beijing-marathon-2026-fairfield-olympic",
    editionId: "beijing-marathon-2026",
    hotelId: "fairfield-beijing-olympic",
    reasonType: "finish_proximity",
    recommendationTitle: "完赛后最省力",
    recommendationReason: "位于奥体终点片区，完赛后返回酒店距离短，适合更看重赛后快速洗澡、休息和恢复的跑者，避免再长距离乘坐公共交通返回住处。",
    evidenceBasis: "racenext_judgment",
    evidenceRefs: [],
    displayOrder: 3,
  },
  {
    recommendationId: "xian-marathon-2026-yazhi-xian-zhonglou-yongningmen",
    editionId: "xian-marathon-2026",
    hotelId: "yazhi-xian-zhonglou-yongningmen",
    reasonType: "start_proximity",
    recommendationTitle: "比赛日最省事",
    recommendationReason: "位于永宁门附近，适合优先步行前往起点，减少比赛日清晨交通的不确定性。",
    evidenceBasis: "racenext_judgment",
    evidenceRefs: [],
    displayOrder: 1,
  },
  {
    recommendationId: "xian-marathon-2026-citigo-xian-zhonglou-nanmen",
    editionId: "xian-marathon-2026",
    hotelId: "citigo-xian-zhonglou-nanmen",
    reasonType: "transport",
    recommendationTitle: "古城内兼顾起跑",
    recommendationReason: "位于钟楼—南门核心区域，在保持起跑便利的同时，也方便把参赛和古城体验结合起来。",
    evidenceBasis: "racenext_judgment",
    evidenceRefs: [],
    displayOrder: 2,
  },
  {
    recommendationId: "xian-marathon-2026-ji-xian-aoti-convention",
    editionId: "xian-marathon-2026",
    hotelId: "ji-xian-aoti-convention",
    reasonType: "finish_proximity",
    recommendationTitle: "全马完赛后更省事",
    recommendationReason: "位于奥体片区，更适合把全马完赛后的返程便利放在首位的跑者；比赛日则需要提前安排前往永宁门起点的交通。",
    evidenceBasis: "racenext_judgment",
    evidenceRefs: [],
    displayOrder: 3,
  },
  {
    recommendationId: "chengdu-marathon-2026-chengdu-jinsha-century",
    editionId: "chengdu-marathon-2026",
    hotelId: "chengdu-jinsha-century",
    reasonType: "runner_feedback",
    recommendationTitle: "往届跑者实测",
    recommendationReason: "位于金沙片区，往届已有成马跑者实际入住，去起点也比较方便，适合希望参考真实参赛住宿经验的跑者。",
    evidenceBasis: "mixed",
    evidenceRefs: [],
    displayOrder: 2,
  },
  {
    recommendationId: "chengdu-marathon-2026-orange-chengdu-yipintianxia-jinsha-museum",
    editionId: "chengdu-marathon-2026",
    hotelId: "orange-chengdu-yipintianxia-jinsha-museum",
    reasonType: "start_proximity",
    recommendationTitle: "起点最直接",
    recommendationReason: "位于金沙遗址核心区域，适合把比赛日清晨少折腾、方便到达起点放在第一位的跑者。",
    evidenceBasis: "racenext_judgment",
    evidenceRefs: [],
    displayOrder: 1,
  },
  {
    recommendationId: "chengdu-marathon-2026-yitel-chengdu-caida-wenhuagong",
    editionId: "chengdu-marathon-2026",
    hotelId: "yitel-chengdu-caida-wenhuagong",
    reasonType: "transport",
    recommendationTitle: "交通更均衡",
    recommendationReason: "位于文化宫片区，在保持金沙起点可达性的同时，也方便赛前赛后的城市出行。",
    evidenceBasis: "racenext_judgment",
    evidenceRefs: [],
    displayOrder: 3,
  },
  {
    recommendationId: "chengdu-marathon-2026-chengdu-hongyu",
    editionId: "chengdu-marathon-2026",
    hotelId: "chengdu-hongyu",
    reasonType: "runner_feedback",
    recommendationTitle: "实用型起点选择",
    recommendationReason: "靠近金沙起点区域，也有往届成都马跑者实际入住反馈，适合不一定要住到起点门口、但希望比赛日出发足够省事的跑者。",
    evidenceBasis: "mixed",
    evidenceRefs: [],
    displayOrder: 4,
  },
  {
    recommendationId: "chengdu-marathon-2026-holiday-inn-chengdu-century-city-east",
    editionId: "chengdu-marathon-2026",
    hotelId: "holiday-inn-chengdu-century-city-east",
    reasonType: "finish_proximity",
    recommendationTitle: "全马完赛后更省事",
    recommendationReason: "位于世纪城片区，更适合把全马完赛后的返程便利放在首位的跑者；比赛日则需要提前前往金沙起点。",
    evidenceBasis: "racenext_judgment",
    evidenceRefs: [],
    displayOrder: 5,
  },
  {
    recommendationId: "tsaigu-kuocang-2026-dada-linhai",
    editionId: "tsaigu-kuocang-2026",
    hotelId: "dada-linhai",
    reasonType: "runner_feedback",
    recommendationTitle: "古城核心·跑者实测",
    recommendationReason: "位于临海古城核心区域，也有往届柴古跑者实际入住经验，适合希望住在起终点附近、同时参考真实参赛住宿体验的跑者。",
    evidenceBasis: "mixed",
    evidenceRefs: [],
    displayOrder: 2,
  },
  {
    recommendationId: "tsaigu-kuocang-2026-sanfuyizhai-linhai",
    editionId: "tsaigu-kuocang-2026",
    hotelId: "sanfuyizhai-linhai",
    reasonType: "start_proximity",
    recommendationTitle: "离起终点最近",
    recommendationReason: "距兴善门很近，适合希望凌晨出门后直接步行去起点、长距离完赛后也尽快回住宿的跑者。",
    evidenceBasis: "racenext_judgment",
    evidenceRefs: [],
    displayOrder: 1,
  },
  {
    recommendationId: "tsaigu-kuocang-2026-taizhou-fuchengyin",
    editionId: "tsaigu-kuocang-2026",
    hotelId: "taizhou-fuchengyin",
    reasonType: "start_proximity",
    recommendationTitle: "酒店型步行方案",
    recommendationReason: "仍在兴善门步行范围内，同时更接近标准酒店住宿形态，适合不太想住小型民宿的跑者。",
    evidenceBasis: "racenext_judgment",
    evidenceRefs: [],
    displayOrder: 3,
  },
  {
    recommendationId: "tsaigu-kuocang-2026-qianshan-m-plus-linhai",
    editionId: "tsaigu-kuocang-2026",
    hotelId: "qianshan-m-plus-linhai",
    reasonType: "start_proximity",
    recommendationTitle: "古城内步行优先",
    recommendationReason: "位于台州府城核心区域，起终点、古城和赛前赛后活动都集中在步行范围内。",
    evidenceBasis: "racenext_judgment",
    evidenceRefs: [],
    displayOrder: 4,
  },
  {
    recommendationId: "tsaigu-kuocang-2026-kaiyuan-mingting-linhai",
    editionId: "tsaigu-kuocang-2026",
    hotelId: "kaiyuan-mingting-linhai",
    reasonType: "start_proximity",
    recommendationTitle: "标准酒店平衡型",
    recommendationReason: "距兴善门比前几家稍远，但仍处于合理步行范围，适合希望住标准酒店、又不想比赛日依赖车辆的跑者。",
    evidenceBasis: "racenext_judgment",
    evidenceRefs: [],
    displayOrder: 5,
  },
  {
    recommendationId: "ninghai-ultra-trail-2026-xiakeju-ninghai-xuxiake",
    editionId: "ninghai-ultra-trail-2026",
    hotelId: "xiakeju-ninghai-xuxiake",
    reasonType: "start_proximity",
    recommendationTitle: "比赛日最省事",
    recommendationReason: "距西门城楼约 1 公里，适合把比赛日清晨少折腾、长距离完赛后尽快回住宿放在第一位的跑者。",
    evidenceBasis: "racenext_judgment",
    evidenceRefs: [],
    displayOrder: 1,
  },
  {
    recommendationId: "ninghai-ultra-trail-2026-atour-ninghai-xizi-international",
    editionId: "ninghai-ultra-trail-2026",
    hotelId: "atour-ninghai-xizi-international",
    reasonType: "start_proximity",
    recommendationTitle: "近起点·标准连锁",
    recommendationReason: "靠近西门城楼，适合希望兼顾比赛日起终点便利和标准连锁住宿体验的跑者。",
    evidenceBasis: "racenext_judgment",
    evidenceRefs: [],
    displayOrder: 2,
  },
  {
    recommendationId: "ninghai-ultra-trail-2026-hanting-ninghai-xizi-plaza",
    editionId: "ninghai-ultra-trail-2026",
    hotelId: "hanting-ninghai-xizi-plaza",
    reasonType: "start_proximity",
    recommendationTitle: "近起点实用备选",
    recommendationReason: "位于西子国际一带，属于西门城楼附近的实用型住宿选择，适合热门比赛期间为近起点酒店多留一个可订备选。",
    evidenceBasis: "racenext_judgment",
    evidenceRefs: [],
    displayOrder: 3,
  },
  {
    recommendationId: "ninghai-ultra-trail-2026-ninghai-world-trade-center",
    editionId: "ninghai-ultra-trail-2026",
    hotelId: "ninghai-world-trade-center",
    reasonType: "race_service",
    recommendationTitle: "县城核心备选",
    recommendationReason: "位于宁海县城核心区域，往届赛事曾作为前往西门城楼的官方接驳点，适合近起点酒店紧张时作为补充选择；2026 接驳安排仍以赛事官方最终通知为准。",
    evidenceBasis: "mixed",
    evidenceRefs: [],
    displayOrder: 4,
  },
  {
    recommendationId: "ninghai-ultra-trail-2026-tiangang-manfei-ninghai",
    editionId: "ninghai-ultra-trail-2026",
    hotelId: "tiangang-manfei-ninghai",
    reasonType: "runner_feedback",
    recommendationTitle: "往届跑者实测",
    recommendationReason: "有往届宁海越野跑者实际入住反馈，酒店曾为赛事调整早餐时间并提供参赛服务；但距西门城楼更远，更适合作为近起点酒店紧张时的备选。",
    evidenceBasis: "mixed",
    evidenceRefs: [],
    displayOrder: 5,
  },
  {
    recommendationId: "shanghai-marathon-2026-atour-shanghai-bund-nanjing-east",
    editionId: "shanghai-marathon-2026",
    hotelId: "atour-shanghai-bund-nanjing-east",
    reasonType: "start_proximity",
    recommendationTitle: "起点最直接",
    recommendationReason: "位于外滩核心区域，适合把比赛日清晨少折腾、稳定前往金牛广场起点放在第一位的跑者。",
    evidenceBasis: "racenext_judgment",
    evidenceRefs: [],
    displayOrder: 1,
  },
  {
    recommendationId: "shanghai-marathon-2026-jinglai-bushe-shanghai-bund",
    editionId: "shanghai-marathon-2026",
    hotelId: "jinglai-bushe-shanghai-bund",
    reasonType: "start_proximity",
    recommendationTitle: "外滩近起点备选",
    recommendationReason: "靠近外滩金牛广场，适合希望住在起点附近、同时为热门比赛多保留一个可订选择的跑者。",
    evidenceBasis: "racenext_judgment",
    evidenceRefs: [],
    displayOrder: 2,
  },
  {
    recommendationId: "shanghai-marathon-2026-metropolo-shanghai-bund-nanjing-road",
    editionId: "shanghai-marathon-2026",
    hotelId: "metropolo-shanghai-bund-nanjing-road",
    reasonType: "start_proximity",
    recommendationTitle: "外滩成熟酒店方案",
    recommendationReason: "位于南京东路外滩片区，兼顾起点便利和成熟酒店住宿体验，适合希望比赛日出发省事、又偏好传统酒店形态的跑者。",
    evidenceBasis: "racenext_judgment",
    evidenceRefs: [],
    displayOrder: 3,
  },
  {
    recommendationId: "shanghai-marathon-2026-radisson-shanghai-olympic-club",
    editionId: "shanghai-marathon-2026",
    hotelId: "radisson-shanghai-olympic-club",
    reasonType: "finish_proximity",
    recommendationTitle: "全马完赛后最省事",
    recommendationReason: "位于徐家汇体育公园一带，更适合把全马完赛后的休息和返程便利放在首位的跑者；比赛日则需要提前前往外滩起点。",
    evidenceBasis: "racenext_judgment",
    evidenceRefs: [],
    displayOrder: 4,
  },
  {
    recommendationId: "shanghai-marathon-2026-metropolo-shanghai-xujiahui-nanhuating",
    editionId: "shanghai-marathon-2026",
    hotelId: "metropolo-shanghai-xujiahui-nanhuating",
    reasonType: "finish_proximity",
    recommendationTitle: "终点侧实用备选",
    recommendationReason: "靠近徐家汇体育公园，适合希望全马完赛后尽快回住宿、同时为终点附近多留一个可订选择的跑者。",
    evidenceBasis: "racenext_judgment",
    evidenceRefs: [],
    displayOrder: 5,
  },
  {
    recommendationId: "guangzhou-marathon-2026-mercure-guangzhou-tianhe-sports-center",
    editionId: "guangzhou-marathon-2026",
    hotelId: "mercure-guangzhou-tianhe-sports-center",
    reasonType: "start_proximity",
    recommendationTitle: "比赛日最省事",
    recommendationReason: "紧邻天河体育中心，适合把比赛日清晨少折腾、稳定前往起点放在第一位的跑者。",
    evidenceBasis: "racenext_judgment",
    evidenceRefs: [],
    displayOrder: 1,
  },
  {
    recommendationId: "guangzhou-marathon-2026-guangzhou-tianhe-hotel-sports-center",
    editionId: "guangzhou-marathon-2026",
    hotelId: "guangzhou-tianhe-hotel-sports-center",
    reasonType: "start_proximity",
    recommendationTitle: "起点旁稳定备选",
    recommendationReason: "位于天河体育中心旁，适合希望住得离起点足够近，同时为热门比赛多保留一个标准酒店选择的跑者。",
    evidenceBasis: "racenext_judgment",
    evidenceRefs: [],
    displayOrder: 2,
  },
  {
    recommendationId: "guangzhou-marathon-2026-ji-guangzhou-tianhe-tiyuxilu",
    editionId: "guangzhou-marathon-2026",
    hotelId: "ji-guangzhou-tianhe-tiyuxilu",
    reasonType: "runner_feedback",
    recommendationTitle: "往届跑者实测",
    recommendationReason: "有往届广州马拉松跑者实际住宿反馈，前往天河体育中心也比较方便，适合希望参考真实参赛住宿经验的跑者。",
    evidenceBasis: "mixed",
    evidenceRefs: [],
    displayOrder: 3,
  },
  {
    recommendationId: "guangzhou-marathon-2026-hotel-indigo-guangzhou-haixinsha",
    editionId: "guangzhou-marathon-2026",
    hotelId: "hotel-indigo-guangzhou-haixinsha",
    reasonType: "finish_proximity",
    recommendationTitle: "完赛后最省事",
    recommendationReason: "位于海心沙一带，更适合把全马完赛后的休息和返程便利放在首位的跑者；比赛日则需要提前前往天河体育中心起点。",
    evidenceBasis: "racenext_judgment",
    evidenceRefs: [],
    displayOrder: 4,
  },
  {
    recommendationId: "guangzhou-marathon-2026-waifiden-guangzhou-tower-zhujiang-new-town",
    editionId: "guangzhou-marathon-2026",
    hotelId: "waifiden-guangzhou-tower-zhujiang-new-town",
    reasonType: "finish_proximity",
    recommendationTitle: "终点侧实用备选",
    recommendationReason: "靠近海心沙终点区域，适合希望完赛后尽快回住宿，同时为终点附近多留一个可订选择的跑者。",
    evidenceBasis: "racenext_judgment",
    evidenceRefs: [],
    displayOrder: 5,
  },
  {
    recommendationId: "shenzhen-100-2026-hampton-shenzhen-dameisha",
    editionId: "shenzhen-100-2026",
    hotelId: "hampton-shenzhen-dameisha",
    reasonType: "start_proximity",
    recommendationTitle: "大梅沙标准酒店首选",
    recommendationReason: "位于大梅沙核心区域，适合 60K、35K 和 10K 跑者优先降低比赛日出发和完赛后的交通不确定性。",
    evidenceBasis: "racenext_judgment",
    evidenceRefs: [],
    displayOrder: 1,
  },
  {
    recommendationId: "shenzhen-100-2026-junyi-seaview-apartment-shenzhen-dameisha",
    editionId: "shenzhen-100-2026",
    hotelId: "junyi-seaview-apartment-shenzhen-dameisha",
    reasonType: "runner_feedback",
    recommendationTitle: "往届跑者实测",
    recommendationReason: "有往届深圳100跑者实际入住反馈，起终点和地铁都比较方便，适合希望参考真实参赛住宿经验的跑者。",
    evidenceBasis: "mixed",
    evidenceRefs: [],
    displayOrder: 2,
  },
  {
    recommendationId: "shenzhen-100-2026-remi-shenzhen-dameisha-seaside-park",
    editionId: "shenzhen-100-2026",
    hotelId: "remi-shenzhen-dameisha-seaside-park",
    reasonType: "start_proximity",
    recommendationTitle: "大梅沙近起点备选",
    recommendationReason: "靠近大梅沙海滨公园，适合希望比赛日少依赖车辆，同时为热门赛事多保留一个可订选择的跑者。",
    evidenceBasis: "racenext_judgment",
    evidenceRefs: [],
    displayOrder: 3,
  },
  {
    recommendationId: "shenzhen-100-2026-zaihaibian-seaview-villa",
    editionId: "shenzhen-100-2026",
    hotelId: "zaihaibian-seaview-villa",
    reasonType: "start_proximity",
    recommendationTitle: "100K 起点优先",
    recommendationReason: "位于大鹏所城、较场尾一带，更适合 100K 跑者把 6:00 起跑前的交通确定性放在首位，避免比赛日凌晨从大梅沙跨区前往起点。",
    evidenceBasis: "racenext_judgment",
    evidenceRefs: [],
    displayOrder: 4,
  },
  {
    recommendationId: "shenzhen-100-2026-tinghai-seaview-residence-dapeng",
    editionId: "shenzhen-100-2026",
    hotelId: "tinghai-seaview-residence-dapeng",
    reasonType: "start_proximity",
    recommendationTitle: "100K 起点侧备选",
    recommendationReason: "位于大鹏所城附近，适合 100K 跑者希望前一晚住在起点侧，同时为大鹏所城附近多保留一个可订选择。",
    evidenceBasis: "racenext_judgment",
    evidenceRefs: [],
    displayOrder: 5,
  },
];

export function getRaceAccommodationRecommendations(editionId: string): Array<{
  hotel: Hotel;
  recommendation: RaceAccommodationRecommendation;
}> {
  return recommendations
    .filter((recommendation) => recommendation.editionId === editionId)
    .sort((left, right) => left.displayOrder - right.displayOrder)
    .map((recommendation) => {
      const hotel = hotels.find((candidate) => candidate.hotelId === recommendation.hotelId);
      if (!hotel) throw new Error(`Unknown accommodation hotel: ${recommendation.hotelId}`);
      return { hotel, recommendation };
    });
}
